// <auto-generated />
namespace DigitalSignage.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _211_Install : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_211_Install));
        
        string IMigrationMetadata.Id
        {
            get { return "201604072101053_2-1-1_Install"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
