// <auto-generated />
namespace DigitalSignage.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2601837_ChangeDisplayIDName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2601837_ChangeDisplayIDName));
        
        string IMigrationMetadata.Id
        {
            get { return "201809140556179_2-6-0-1837_ChangeDisplayIDName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
