name: build C# projects
on:
  push:
    paths-ignore:
    - 'README.md'
    - 'Documentation/**'
  workflow_dispatch:

jobs:
  setup-dotnet:
    name: setup and build windows
    runs-on: windows-latest

    env:
      Solution_Name: src\DigitalSignageAll.sln 

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore src\DigitalSignageAll.sln
    - run: dotnet build src/DigitalSignage.Data
    - run: dotnet build src/DigitalSignage.Infrastructure

    - uses: actions/cache/save@v4
      id: save-compiles
      with:
        path: ./src/*
        key: csharp${{ github.sha }}

  test-importCli:
    needs: setup-dotnet
    name: run ImportCli tests
    runs-on: windows-latest
    steps:  
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache/restore@v4
      id: load-deps
      with:
        path: ./src/*
        key: csharp${{ github.sha }}

    - run: dotnet build src/DigitalSignage.ImportCLI.NUnitTests
    - name: Test
      run: dotnet test --no-build src/DigitalSignage.ImportCLI.NUnitTests/DigitalSignage.ImportCLI.NUnitTests.csproj

  csharp-unittests:
    needs: setup-dotnet
    name: run unit tests
    runs-on: windows-latest
    steps:  
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache/restore@v4
      id: load-deps
      with:
        path: ./src/*
        key: csharp${{ github.sha }}

    - name: Test
      run: dotnet test src/DigitalSignage.UnitTests/DigitalSignage.UnitTests.csproj

#    - name: setup-msbuild all projects
#      uses: microsoft/setup-msbuild@v1.1
#      with:
#        msbuild-architecture: "x64"
#    - run: msbuild src\DigitalSignageAll.sln

  build-webapi:
    needs: setup-dotnet
    name: build WebAPI Server
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache/restore@v4
      id: load-deps
      with:
        path: ./src/*
        key: csharp${{ github.sha }}
    - uses: kzrnm/get-net-sdk-project-versions-action@v2
      id: get-version-wa
      with:
        proj-path: ./src/DigitalSignage.dn.WebApiCore/DigitalSignage.dn.WebApiCore.csproj 
  
    - run: dotnet build src/DigitalSignage.dn.WebApiCore
    - name: Build publish files for WebAPI-Server
      run: dotnet publish src\DigitalSignage.dn.WebApiCore -c Release -a x64 --os win --output ./src/DigitalSignage.dn.WebApiCore/publish
    - name: 'Upload WebAPI-Server Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: WebAPI-Server@${{steps.get-version-wa.outputs.version}}
        path: ./src/DigitalSignage.dn.WebApiCore/publish
        retention-days: 30

  build-Display-Control:
    needs: setup-dotnet
    name: build DisplayControl service
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache/restore@v4
      id: load-deps
      with:
        path: ./src/*
        key: csharp${{ github.sha }}
    - uses: kzrnm/get-net-sdk-project-versions-action@v2
      id: get-version-dc
      with:
        proj-path: ./src/DigitalSignage.dn.DisplayControl/DigitalSignage.dn.DisplayControl.csproj  

    - run: dotnet build src/DigitalSignage.dn.DisplayControl
    - name: Build publish files for DisplayControl
      run: dotnet publish src\DigitalSignage.dn.DisplayControl -c Release --output ./src/DigitalSignage.dn.DisplayControl/publish
    - name: 'Upload DisplayControl Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: DisplayControl@${{steps.get-version-dc.outputs.version}}
        path: ./src/DigitalSignage.dn.DisplayControl/publish
        retention-days: 30

  build-ImportCLI:
    needs: setup-dotnet
    name: build ImportCLI service
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache/restore@v4
      id: load-deps
      with:
        path: ./src/*
        key: csharp${{ github.sha }}
    - uses: kzrnm/get-net-sdk-project-versions-action@v2
      id: get-version-imp
      with:
        proj-path: ./src/DigitalSignage.ImportCLI/DigitalSignage.ImportCLI.csproj 

    - run: dotnet build src/DigitalSignage.ImportCLI
    - name: Build publish files for ImportCLI
      run: dotnet publish src\DigitalSignage.ImportCLI -c Release -a x64 --os win --output ./src/DigitalSignage.ImportCLI/publish
    - name: 'Upload ImportCLI Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: ImportCLI@${{steps.get-version-imp.outputs.version}}
        path: ./src/DigitalSignage.ImportCLI/publish
        retention-days: 30

  build-DataAPI:
    needs: setup-dotnet
    name: build DataAPI Server
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache/restore@v4
      id: load-deps
      with:
        path: ./src/*
        key: csharp${{ github.sha }}
    - uses: kzrnm/get-net-sdk-project-versions-action@v2
      id: get-version-dapi
      with:
        proj-path: ./src/DigitalSignage.DataAPI/DigitalSignage.DataAPI.csproj 

    - run: dotnet build src/DigitalSignage.DataAPI
    - name: Build publish files for DataAPI-Server
      run: dotnet publish src\DigitalSignage.DataAPI -c Release -a x64 --os win --output ./src/DigitalSignage.DataAPI/publish
    - name: 'Upload DataAPI-Server Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: DataAPI-Server@${{steps.get-version-dapi.outputs.version}}
        path: ./src/DigitalSignage.DataAPI/publish
        retention-days: 30

  dependencies-dssuite:
    name: setup and build web apps
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: install dependencies 
        working-directory: ./src/ds-suite
        run: npm ci

      - uses: actions/cache/save@v4
        id: save-deps
        with:
          path: ./src/ds-suite/*
          key: wa${{ github.sha }}

  build-dsmanager:
    needs: dependencies-dssuite
    name: build display-manager
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: actions/cache/restore@v4
        id: load-deps
        with:
          path: ./src/ds-suite/*
          key: wa${{ github.sha }}
  
      - name: build display-manager
        working-directory: ./src/ds-suite
        run: npm run build:dsmanager

      - name: 'Upload web app artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: ds-manager
          path: ./src/ds-suite/dist/*.zip
          retention-days: 30

  build-displays:
    needs: dependencies-dssuite
    name: build displays
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: actions/cache/restore@v4
        id: load-deps
        with:
          path: ./src/ds-suite/*
          key: wa${{ github.sha }}
      - name: build displays
        working-directory: ./src/ds-suite
        run: npm run build:displays

      - name: 'Upload web app artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: displays
          path: ./src/ds-suite/dist/*.zip
          retention-days: 30

  build-roomcontrol:
    needs: dependencies-dssuite
    name: build roomcontrol
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: actions/cache/restore@v4
        id: load-deps
        with:
          path: ./src/ds-suite/*
          key: wa${{ github.sha }}
      - name: build roomcontrol
        working-directory: ./src/ds-suite
        run: npm run build:roomcontrol
        
      - name: 'Upload web app artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: roomcontrol
          path: ./src/ds-suite/dist/*.zip
          retention-days: 30


  build-ds-webapps:
    name: build all new webapps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: install dependencies 
        working-directory: ./src/ds-webapps
        run: npm ci

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ./src/ds-webapps

      - name: build all
        working-directory: ./src/ds-webapps
        run: npm run build
        
      - name: 'Upload web app artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: ds-webapps@${{ steps.package-version.outputs.current-version}}
          path: ./src/ds-webapps/dist/
          retention-days: 7
    
# #the project is targetting windows
#  build-displayControl-linux:
#    needs: setup-dotnet
#    name: build displayControl app for linux
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v4
#      with:
#        dotnet-version: 8.0.x
#        
#    - name: Restore dependencies
#      run: dotnet restore ./src/DigitalSignageAll.sln
#
#    - name: Build
#      uses: actions/setup-dotnet@v4
#      with:
#        dotnet-version: 8.0.x
#    - run:  dotnet build ./src/DigitalSignage.dn.DisplayControl/DigitalSignage.dn.DisplayControl.csproj
#
#    - name: Build publish files for DisplayControl
#      run: dotnet publish ./src/DigitalSignage.dn.DisplayControl -c Release --output ./src/DigitalSignage.dn.DisplayControl/publish
#    - name: 'Upload DisplayControl-linux Artifact'
#      uses: actions/upload-artifact@v4
#      with:
#        name: DisplayControl-ubuntu
#        path: ./src/DigitalSignage.dn.DisplayControl/publish
#        retention-days: 30
